"""updated user token model

Revision ID: 1b6ffd69695b
Revises: 889ff2842c6a
Create Date: 2026-06-11 09:38:12.757162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6ffd69695b'
down_revision: Union[str, Sequence[str], None] = '889ff2842c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True ) 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
